# Enable local FILE storage
polaris.features.ALLOW_INSECURE_STORAGE_TYPES=true
polaris.features.ALLOW_SPECIFYING_FILE_IO_IMPL=true
polaris.features.SKIP_CREDENTIAL_SUBSCOPING_INDIRECTION=true
polaris.readiness.ignore-severe-issues=true
polaris.features."SUPPORTED_CATALOG_STORAGE_TYPES"=["FILE","S3","GCS","AZURE"]

# Database (Postgres)
polaris.persistence.type=relational-jdbc
